### PR TITLE
As7 4203 messaging deployment

### PR DESCRIPTION
**Pull request by jmesnil**
put the messaging deployment inside the Web archive and update the readme so that it is no longer necessary to modify standalone-full.xml

### CODE REVIEW

**Comment by mmusgrov** [comment]
This is identical to what I was using before I hit the issue.

Have you fixed something on your side?

Mike

**Comment by jmesnil** [comment]
On Thu, Mar 29, 2012 at 11:49 AM, mmusgrov
reply@reply.github.com
wrote:

> This is identical to what I was using before I hit the issue.
> 
> Have you fixed something on your side?

nothing. I was using AS7 master branch.

**Comment by mmusgrov** [comment]
So are you saying that my quickstart is recovering the missing message?

Mike

**Comment by jmesnil** [comment]
yes. it works whether the queue is deployed through the web archive or with standalone-full.xml

**Pull request closed without merging**
